language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: dependencies="--prefer-lowest"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $dependencies

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/phpunit --coverage-clover coverage-clover.xml

after_script:
  - bin/ci-detector dump
  - env

after_success:
  - travis_retry php vendor/bin/coveralls -v
