language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES="--prefer-lowest"
    - name: "Code style and static analysis"
      php: 7.4
      before_install:
        - phpenv config-rm xdebug.ini
      script:
        - composer lint
        - composer analyze
      after_script: ~
      after_success: ~

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $DEPENDENCIES

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - bin/ci-detector dump
  - env

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
