language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: dependencies="--prefer-lowest"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $dependencies

before_script:
#  - unset TRAVIS # To not interfere with tests

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/phpunit --coverage-clover coverage-clover.xml

after_script:
  - env

after_success:
  - travis_retry php vendor/bin/coveralls -v
